---
title: "Writing01-Middle Bits Formula"
description: |
  学术性的写作
author:
  - name: Jason ZHOU
    url: 
date: last-modified
categories:
  - 英语
  - 写作
  - "2023"
image: ""

---
## Introduction 
The Introduction Formula 简介公式
When I arrived at UBC, my colleague John Ries, who had been hired the year before, explained to me that Jim Brander had given him a formula for writing introductions. I’m afraid I didn’t pay much attention at the time because I thought it would stifle my creative juices (is that a mixed metaphor?). Finally, I think I ended up internalizing the rules and now I thought I should make them explicit because they have served us well and I wish I could referee more papers that follow them.
当我到达UBC时，我的同事约翰·里斯（John Ries）向我解释说，吉姆·布兰德（Jim Brander）给了他一个写介绍的公式。
恐怕我当时没有太注意，因为我认为这会扼杀我的创造力（这是一个混合的比喻吗？）。
最后，我想我最终内化了规则，现在我想我应该把它们明确化，因为它们对我们很有帮助，我希望我能裁判更多遵循它们的论文。

Hook: Attract the reader’s interest by telling them that this paper relates to something interesting. What makes a topic interesting? Some combination of the following attributes makes Y something worth looking at.
胡克：通过告诉读者这篇论文与一些有趣的事情有关来吸引他们的兴趣。
是什么让一个话题变得有趣？以下属性的某种组合使 Y 值得一看。

Y matters: When Y rises or falls, people are hurt or helped.
Y很重要：当Y上升或下降时，人们会受到伤害或帮助。

Y is puzzling: it defies easy explanation.
Y令人费解：它无法轻易解释。

Y is controversial: some argue one thing while other say another.
Y是有争议的：有些人争论一件事，而另一些人说另一件事。

Y is big (like the service sector) or common (like traffic jams).
Y 是大（如服务业）或常见（如交通拥堵）。

Things to avoid: 要避免的事项：
The bait and switch : promising an interesting topic but delivering something else, in particular, something boring.
诱饵和开关 ：承诺一个有趣的话题，但提供其他东西，特别是无聊的东西。

“all my friends are doing it” : presenting no other motivation for a topic than that other people have written papers on it.
“我所有的朋友都在这样做”：除了其他人写过关于某个主题的论文之外，没有其他动机。

Question: Tell the reader what this paper actually does. Think of this as the point in a trial where having detailed the crime, you now identify a perpetrator and promise to provide a persuasive case. The reader should have an idea of a clean research question that will have a more or less satisfactory answer by the end of the paper. Examples follow below. The question may take two paragraphs. At the end of the first (2nd paragraph of the paper) or possibly beginning of the second (3rd paragraph overall) you should have the “This paper addresses the question” sentence.
问：告诉读者这篇论文到底做了什么。
将此视为审判中的要点，在详细说明犯罪之后，您现在确定肇事者并承诺提供有说服力的案例。
读者应该对一个干净的研究问题有一个想法，在论文结束时会有一个或多或少令人满意的答案。
示例如下。
这个问题可能需要两段。
在第一篇（论文的第2段）的末尾或第二段的开头（第3段），你应该有“本文解决了问题”的句子。

Antecedents: Identify the prior work that is critical for understanding the contribution this paper will make. The key mistake to avoid here are discussing papers that are not essential parts of the intellectual narrative leading up to your own paper. Give credit where due but establish, in a non-insulting way, that the prior work is incomplete or otherwise deficient in some important way.
前因：确定对理解本文将做出的贡献至关重要的先前工作。
这里要避免的关键错误是讨论那些不是导致你自己的论文的知识叙事的重要组成部分的论文。
在适当的情况下给予荣誉，但以非侮辱性的方式确定先前的工作不完整或在某些重要方面存在缺陷。

Value-Added: Describe approximately 3 contributions this paper will make relative to the antecedents. This paragraph might be the most important one for convincing referees not to reject your paper. A big difference between it and the earlier “question” paragraph is that the contributions should make sense only in light of prior work whereas the basic research question of the paper should be understandable simply in terms of knowing the topic (from the hook paragraph). John suggests that “Antecedents” and “Value-added” may be intertwined. They may also take up to 3 paragraphs.
增值：描述本文相对于前因的大约 3 个贡献。
这一段可能是说服审稿人不要拒绝你的论文的最重要的一段。
它与前面的“问题”段落之间的一个很大区别是，贡献应该只在先前的工作下有意义，而论文的基础研究问题应该只是在了解主题方面（从钩子段落）来理解。
约翰认为，“前因”和“增值”可能是交织在一起的。
它们最多也可以占用 3 个段落。

Road-map: Outline the organization of the paper. Avoid writing an outline so generic that it could apply to any paper (“the next section is the middle of the paper and then we have the end”). Instead customize the road map to the project and possibly mention pivotal “landmarks” (problems, solutions, results…) that will be seen along the way. But keep this short because many readers will now be eager to get to the heart of the paper.
路线图：概述论文的组织结构。
避免写一个过于笼统的大纲，以至于它可以适用于任何论文（“下一部分是论文的中间，然后我们结束了”）。
相反，自定义项目的路线图，并可能提及在此过程中将看到的关键“里程碑”（问题，解决方案，结果......）。
但请保持简短，因为许多读者现在会渴望了解论文的核心。

Brander suggests that you write the intro first but then read and edit it every time you compose other parts of the paper. Thus by the end, the intro will have received more attention, more times, than any other part of the paper. The introduction is not just important because of the “first impressions” idea that it will tilt the referee for or against you (though it probably will). It is also vital to making sure you know yourself what you are doing in the paper and why. If you can’t write a good introduction, then you may be writing the wrong paper.
布兰德建议你先写引言，然后在每次撰写论文的其他部分时阅读和编辑它。
因此，到最后，引言将比论文的任何其他部分受到更多的关注，更多的次数。
引言之所以重要，不仅仅是因为“第一印象”的想法，即它会让裁判倾向于支持或反对你（尽管它可能会）。
确保您知道自己在论文中做什么以及为什么这样做也很重要。
如果你写不出一个好的介绍，那么你可能写错了论文。

## Middle 
The “middle bits” are everything that is not the introduction or the conclusion, so here is a formula for those. Now, I am not saying “here is the right formula for those”; this is something that has worked for me by reducing the amount of uncertainty I face when writing the typical paper. Let’s flesh out each section.
“中间位”是不是引言或结论的所有内容，所以这里有一个公式。
现在，我并不是说“这是正确的公式”;这对我来说是有用的，减少了我在撰写典型论文时面临的不确定性。
让我们充实每个部分。

Theoretical Framework 理论框架
Primitives: What are the preferences and/or technology like?
基元：偏好和/或技术是什么样的？
Variables: What are the choice (i.e., theoretically endogenous) variables? What are the parameters (i.e., theoretically exogenous variables)?
变量：选择变量（即理论上是内生的）变量是什么？参数是什么（即理论上的外生变量）？
Assumptions: What assumptions are you making about preferences and/or technology? What assumptions are you making about the choice variables? What assumptions are you making about the parameters?
假设：您对偏好和/或技术做出了哪些假设？您对选择变量做了哪些假设？您对参数做了哪些假设？
Maximization Problem: What are the agents you are studying maximizing? What is the Lagrangian?
最大化问题：您正在研究最大化的代理是什么？什么是拉格朗日量？
First-Order Conditions: Self-explanatory. In some cases where it is not obvious that you are solving for a maximum or a minimum, you’ll want to show the second-order conditions as well.
一阶条件：不言自明。
在某些情况下，您求解最大值或最小值并不明显，您还需要显示二阶条件。

Testable Prediction: State your main testable prediction. Generally, this should map one-to-one with the empirical framework.
可测试预测：陈述您的主要可测试预测。
一般来说，这应该与经验框架一对一地映射。

Proof: Prove your main testable prediction. Here, go for simplicity rather than elegance–why go for a proof by construction when a proof by contradiction will do just fine?
证明：证明您主要的可测试预测。
在这里，追求简单而不是优雅——当矛盾证明就可以了，为什么要通过构造来证明呢？
Other Results and Proofs: There might be some side results you can both demonstrate in theory and test empirically. Generally, I think one paper should do one big thing–but there are exceptions.
其他结果和证明：您可能有一些侧面结果，您可以在理论上证明和经验测试。
一般来说，我认为一篇论文应该做一件大事——但也有例外。

Empirical Framework 实证框架
Estimation Strategy: What equations will you estimate? How will you estimate them? How will you treat the standard errors? What is the hypothesis test of interest for your main testable prediction? This is why there should generally be a one-to-one mapping from the main testable prediction to the empirical framework. If your outcome variable or variable of interest needs to be constructed or estimated, this is where you’d discuss it.
估计策略：您将估计哪些方程？您将如何估算它们？您将如何处理标准错误？您的主要可检验预测感兴趣的假设检验是什么？这就是为什么通常应该有一个从主要可测试预测到经验框架的一对一映射。
如果你的结果变量或感兴趣的变量需要构建或估计，这就是你讨论它的地方。

Identification Strategy: What would the ideal data set look like to study your question? How close are you to that ideal, and what prevents you from getting closer? Then, discuss in turn how your identification strategy deals or not with (i) unobserved heterogeneity, (ii) reverse causality or simultaneity, and (iii) measurement error. Also think about what a violation of the stable unit treatment value assumption looks like here (does one observation getting treated somehow affect the outcome of another observation?), and whether you can somehow test for it.
识别策略：研究您的问题的理想数据集是什么样子的？你离那个理想有多近，是什么阻止你越来越近？然后，依次讨论您的识别策略如何处理 （i） 未观察到的异质性，（ii） 反向因果关系或同时性，以及 （iii） 测量误差。
还要考虑这里违反稳定单位处理值假设的情况（一个观察值得到处理是否以某种方式影响另一个观察的结果？），以及您是否可以以某种方式对其进行测试。

Data and Descriptive Statistics
数据和描述性统计
Data: When was it collected? Where? Why? By whom? How was the sample selected? Who was interviewed, or how were the data collected? What is the sample size? How does it compare to the population of interest? Do you lose any observations? Why? Did you have to impute any values and, if so, how did you do it? Are any variables proxies for the real thing? What does each variable measure, exactly, or how was it constructed?
数据：何时收集？哪里？为什么？由谁？样品是如何选择的？谁接受了采访，或者数据是如何收集的？样本量是多少？它与感兴趣的人群相比如何？你失去任何观察吗？为什么？您是否必须估算任何值，如果是，您是如何做到的？是否有任何变量代理真实的东西？每个变量究竟测量什么，或者它是如何构造的？
Descriptive Statistics: This is simple enough. If you choose to describe the contents of your table of descriptive statistics, tell a story about them, don’t just write up a boring enumeration of means.
描述性统计：这很简单。
如果你选择描述描述性统计表的内容，讲一个关于它们的故事，不要只是写一个无聊的枚举。

Balance Tests: In cases where you’re looking at a dichotomous (or categorical) variable of interest, how do the treatment and comparison sub-samples differ along the mean of the variables discussed under the previous sub-section?
平衡测试：如果您正在查看感兴趣的二分类（或分类）变量，则处理和比较子样本在上一个小节中讨论的变量的平均值上有何不同？
Results and Discussion 结果和讨论
Preliminary (Nonparametric?) Results: An image is worth 1,000 words. If you can somehow plot the relationship of interest in a two-way scatter with a regression line fit through it, or using kernel density estimates for treatment and comparison, it helps people see for themselves that there is a difference in outcomes in response to your variable of interest.
初步（非参数？结果：一张图片胜过 1，000 个字。
如果您可以以某种方式绘制双向散点中的兴趣关系，并通过回归线拟合它，或者使用核密度估计值进行处理和比较，则可以帮助人们亲眼看到响应您感兴趣的变量的结果存在差异。

Core (Parametric) Results: This is your core test of your main testable prediction. Here, there is no need to go into a discussion of the sign of each significant control variable, unless such a discussion is somehow germane to your core testable prediction.
核心（参数）结果：这是主要可测试预测的核心测试。
在这里，没有必要讨论每个重要控制变量的符号，除非这样的讨论在某种程度上与你的核心可测试预测密切相关。

Robustness Checks: Those are as important as your core results. Do not neglect them. Slice and dice the data in as many ways as possible, sticking many of these results in an appendix, to show that the main testable predictions is supported by the data and that you haven’t cherry-picked your results. If you use an IV, this is where you’d entertain potential violations of the exclusion restrictions, and test for them one by one. Or maybe you can test for the mechanisms through which your variable of interest affects your outcome of interest.
稳健性检查：这些与您的核心结果一样重要。
不要忽视它们。
以尽可能多的方式对数据进行切片和切块，将其中许多结果粘贴在附录中，以表明主要的可测试预测得到了数据的支持，并且您没有精心挑选结果。
如果您使用 IV，您可以在此处考虑可能违反排除限制的情况，并逐个测试它们。
或者，也许您可以测试感兴趣的变量影响您感兴趣的结果的机制。

Extensions: This is where I might explore treatment heterogeneity, or split my sample between men and women, rural and urban, or by industry.
扩展：这是我可能探索治疗异质性的地方，或者将我的样本分为男性和女性，农村和城市，或按行业划分。

Limitations: No empirical result is perfect. How is internal validity limited? How is external validity limited? What are your results not saying, i.e., what mistakes might people make in interpreting them?
局限性：没有经验结果是完美的。
内部有效性如何受到限制？外部有效性如何受到限制？你的结果没有说明什么，即人们在解释它们时可能会犯什么错误？
There it is. It does not get much more complicated than that, and the above skeleton is the right structure for the papers that I write about 90 percent of the time. Note:
就是这样。
没有比这更复杂的了，上面的骨架是我大约90%的时间写论文的正确结构。
注意：
No separate “literature review” section. In a thesis, you would definitely want a literature review between the introduction and the theoretical framework. But in a paper to be submitted to a journal, your literature review should be a one-paragraph affair in your introduction explaining how your work relates to the closest five to seven studies on the topic.
没有单独的“文献综述”部分。
在论文中，您肯定希望在引言和理论框架之间进行文献综述。
但是在一篇提交给期刊的论文中，你的文献综述应该是引言中的一段话，解释你的工作与关于该主题的最接近的五到七项研究的关系。

You might want to have a section titled “Background” between the introduction and the theoretical framework. This is especially so when you study a legislative change, a new policy whose details are important or, in an IO paper, the features of the market you are studying. This can either be a substitute for or a complement to the theoretical framework.
您可能希望在引言和理论框架之间有一个标题为“背景”的部分。
当您研究立法变更、细节很重要的新政策或 IO 文件中您正在研究的市场特征时，尤其如此。
这可以替代或补充理论框架。

You might not need a theoretical framework. Some questions are old (e.g., the effects of land rights on agricultural productivity) and the theory behind them is well documented and does not need to be restated.
你可能不需要理论框架。
有些问题已经过时（例如，土地权对农业生产力的影响），其背后的理论有据可查，无需重述。

The order between the “Empirical Framework” and “Data and Descriptive Statistics” sections can sometimes be switched. Go with what is logical here.
“经验框架”和“数据和描述性统计”部分之间的顺序有时可以切换。
按照这里的逻辑。

You might have noticed that I list “limitations” both under “Results and Discussion” and in my conclusion formula. I really think limitations should be emphasized that way. This is especially true if your work has any policy relevance; you don’t want anyone to interpret your results in ways they should not be interpreted.
您可能已经注意到，我在“结果和讨论”和结论公式中都列出了“限制”。
我真的认为应该以这种方式强调局限性。
如果您的工作与政策相关，则尤其如此;您不希望任何人以不应该被解释的方式解释您的结果。

## Conclusion 
Since I joined Minnesota in 2013, I have had the privilege of teaching the second-year paper seminar, which all of our PhD students are required to take, and in which they get to write an entire research paper from start to finish.
自从我2013年加入明尼苏达州以来，我有幸教授第二年的论文研讨会，我们所有的博士生都必须参加，他们可以从头到尾写一篇完整的研究论文。

Every fall, I go over Keith Head’s tremendously useful Introduction Formula, which has the double benefit of (i) minimizing the amount of uncertainty you face when writing the introduction for your research papers, and (ii) ensuring that you follow the social norm(s) surrounding how an introduction should be written for an economics paper. Then, because there isn’t much more to the introduction formula than Hook-Research Question-Antecedents-Value Added-Roadmap, I show students examples of introductions written using that formula, to show them that the formula does indeed work.
每年秋天，我都会复习基思·海德（Keith Head）非常有用的引言公式，该公式具有双重好处：（i）最大限度地减少您在为研究论文撰写引言时面临的不确定性，以及（ii）确保您遵循围绕如何为经济学论文撰写引言的社会规范。
然后，因为介绍公式除了钩子研究问题-前因-增值路线图之外没有更多的东西，所以我向学生展示了使用该公式编写的介绍示例，向他们展示该公式确实有效。

When I taught the introduction formula last week, someone asked: “But how should we write the conclusion?” Beyond what I had learned in high school, I didn’t really have a good answer, so I figured I should look around and see if there are any obvious social norms surrounding how conclusions are written for economics papers; I found nothing. Even William Thomson’s otherwise wonderful Guide for the Young Economist has nothing about how to write conclusions.
上周我教介绍公式时，有人问：“但是我们应该怎么写结论呢？除了我在高中学到的东西之外，我真的没有一个好的答案，所以我想我应该环顾四周，看看是否有任何明显的社会规范来写经济学论文的结论;我什么也没找到。
就连威廉·汤姆森（William Thomson）那本精彩的《青年经济学家指南》（Guide for the Young Economist）也对如何写结论一无所知。

The Conclusion Formula 结论公式
Many economics papers titled their conclusion “Summary and Concluding Remarks,” which is a pretty good indication of how your conclusion should proceed. What I learned in high school was that a good conclusion should have two main parts: (i) a summary of what you have spent the several pages before the conclusion doing, and (ii) the way forward.
许多经济学论文将他们的结论命名为“总结和结论”，这很好地表明了你的结论应该如何进行。
我在高中学到的是，一个好的结论应该有两个主要部分：（i）总结你在结论之前花了几页的时间，以及（ii）前进的方向。

I am not claiming to be a master at writing conclusions, but I have written enough of them to get a good sense of what works, and to provide the following guidelines to cut on the transaction costs other people face when writing conclusions. Strictly speaking, a conclusion should be structured as follows:
我并不是说自己是写结论的大师，但我已经写了足够多的结论，以便很好地了解什么是有效的，并提供以下指导方针来减少其他人在写结论时面临的交易成本。
严格来说，结论的结构应该如下：
Summary. You’ve surely heard that when writing a research paper, “tell them what you’re going to tell them, tell them what you want to tell them, and tell them what you just told them.” This part is obviously tedious–you have just spent 40-some pages telling them–but it needs to be there, and it needs to be different enough from the abstract and the introduction. Note that I didn’t say it needs to say something new; it just needs to be different enough. If possible, tell a story.
总结。
你肯定听说过，在写研究论文时，“告诉他们你要告诉他们什么，告诉他们你想告诉他们什么，告诉他们你刚刚告诉他们的事情。
这部分显然很乏味——你刚刚花了40多页来告诉他们——但它需要在那里，它需要与摘要和引言足够不同。
请注意，我没有说它需要说一些新的东西;它只需要足够不同。
如果可能的话，讲一个故事。

Limitations. Some people like to have a “Limitations” section at the end of their results section; I like to have that myself. But the conclusion should also emphasize the limitations of your approach.
局限性。
有些人喜欢在结果部分的末尾有一个“限制”部分;我喜欢自己拥有它。
但结论也应该强调你的方法的局限性。

Implications for Policy. Presumably, your work has some sort of implication for how policy is made in the real world. This will not always be the case–some papers make a purely technical point, or a point that is only ancillary when it comes to making other policy-related points–but I would guess that since you are reading this blog, there is a high likelihood that what you are working on has some policy implications. Discuss what those implications are, but don’t make claims that are not supported by your results, and try to assess the cost of what you propose in comparison to its benefits. You can do so somewhat imperfectly (if I were a betting man, I would bet that this is where the phrase “back-of-the-envelope calculation” comes up the most often in economics papers), since the point of your work was presumably about only one side of that equation–usually the benefits of something, sometimes its costs, but rarely both. In two or three sentences, can you identify the clear winners and losers of a given policy implications? Its political feasibility? How easy or hard it would be to implement?
对政策的影响。
据推测，你的工作对现实世界中政策的制定方式有某种影响。
情况并非总是如此——有些论文提出了纯粹的技术观点，或者只是在提出其他政策相关观点时只是辅助的观点——但我猜，既然你正在阅读这个博客，你正在做的事情很可能有一些政策影响。
讨论这些影响是什么，但不要提出结果不支持的声明，并尝试评估您提出的成本与其益处的比较。
你可以做得有点不完美（如果我是一个赌徒，我敢打赌，这就是经济学论文中“粗略计算”这个词最常出现的地方），因为你的工作重点可能只是关于这个等式的一面——通常是某件事的好处，有时是成本，但很少两者兼而有之。
用两三句话，你能确定给定政策含义的明显赢家和输家吗？它的政治可行性？实施起来有多容易或多难？
Implications for Future Research. Finally, your work is not perfect. Your theoretical contribution could be generalized, or broadened by relaxing certain assumptions. Your empirical contribution could probably benefit from better causal identification for better internal validity. Even with a randomized controlled trial (RCT) with perfect compliance, you might want to run the same RCT in additional locations for external validity. If you are writing a follow-up paper, this is a good place to set the stage for it.*
对未来研究的影响。
最后，你的工作并不完美。
你的理论贡献可以被概括，或者通过放宽某些假设来扩大。
您的实证贡献可能会受益于更好的因果识别，以获得更好的内部有效性。
即使有完全依从性的随机对照试验（RCT），您可能希望在其他位置运行相同的RCT，以确保外部有效性。
如果您正在撰写后续论文，这是为其奠定基础的好地方。

This is why I often tell students not to look for research ideas in the conclusions of the papers they read, because conclusions either list (i) ideas that are so difficult to execute that the authors of the papers you’re reading didn’t think it was worth exploring them, or (ii) ideas that those same authors are already working on.
*这就是为什么我经常告诉学生不要在他们阅读的论文的结论中寻找研究想法，因为结论要么列出（i）难以执行的想法，以至于你正在阅读的论文的作者认为不值得探索它们，要么（ii）这些作者已经在研究的想法。
