---
title: "Writing04-Environment & Economic"
description: |
  学术性的写作
author:
  - name: Jason ZHOU
    url: 
date: last-modified
categories:
  - 英语
  - 写作
  - "2023"
image: ""

---

## 选题 

大家如果有一定的科研经历应该知道选题是论文里面最重要也是最困难的部分。以前在介绍美国经济学博士项目的文章中写到，博士生通常在第二年或者第三年要整整花一两年的时间来找到一个比较好和比较适合的题目。美国导师通常不会给学生题目，都是要自己去找，所以这个过程比较痛苦。一个比较好的题目确实不太好找，主要是竞争激烈，很容易想到的题目都被别人做过了。所以大家对选题难要有一定的预期。接下来根据我们这篇文章来谈一谈如果找到一个好题目。

首先，要对文献非常熟悉。做科研不是完全天马行空，乱拍脑子找想法，一般都是在大量阅读文献基础上想出的贡献，这就要求对文献要非常非常熟悉。当然不是什么文章都值得读，我一般只会看领域内顶刊，即top field或者之上的文章。而且看的时候只会看Introduction的部分，不会特别去看细节，主要是看这篇文章主要做了什么贡献，用一两句话就可以讲清楚的。如果有特别需要模仿或者参考的文章，再去看细节。

我们这篇文章主要研究的是空气污染如何影响企业生产率的，大的领域属于环境经济学/发展经济学/公共经济学，往小了说属于研究空气污染如何影响经济活动的。这一支领域主要的motivation是衡量空气污染的外部性成本，进而为空气污染监管政策提供benefit side的证据。经典文献也就几十篇左右。这个领域刚开始主要研究空气污染对健康，大部分是对死亡率的影响。后来慢慢扩展到不同的领域，像认知能力、精神健康、劳动供给、劳动生产率等，基本上可以概括为空气污染对人力资本的影响。人力资本HumanCapital是一个比较广泛的概念，很多经济学变量都可以跟人力资本联系上。

我们的文章从更小的领域讲算是研究空气污染对劳动生产率的影响。不做这个领域的人可能都不会想到空气污染还能影响劳动生产率。其实这个机制很好理解，有很多证据说明空气污染会影响人类健康，健康受影响了工作的效率自然会差。此外还有一些间接的渠道，比如影响孩子的健康导致父母分心照顾孩子进而影响父母的生产率等。生产率Productivity是经济学很重要的一个变量，Mankiw十大经济学原理里一个就是讲一个国家生活水平取决于其生产商品和服务的能力，其实就是生产率。所以空气污染对生产率影响的一些文章都发表的很好。 

最早研究空气污染对生产率影响的文章是JoshuaGraff Zivin跟MattNeidell 2012年发表在AmericanEconomic Review上面的一篇文章，原文链接在这里。https://www.aeaweb.org/articles?id=10.1257/aer.102.7.3652Josh是加州大学圣地亚哥的教授，Matt是哥伦比亚大学的教授。两个人做了很多关于空气污染和气候变化方面的文章，是这个领域的大牛。 这篇文章的方法和数据其实非常简单，用了加州一个农场的数据，看臭氧比较高的时候工人摘水果的效率是不是低一些。我曾经跟Josh聊过，请教他怎么把如此简单的故事发表在经济学最顶级期刊AER上面。他说他跟合作者Matt曾经花了两个月的时间就为了写Introduction前两段。后来反复敲定，决定还是开始就讲productivity的重要性。然后讲这么重要的一个变量会不会受到环境的影响。因为这是第一篇做空气污染对生产率影响的文章，所以发在了AER上面。

之前跟很多主编喜欢看到This is the first study on ….类似的文字。 Josh跟Matt之后跟其他的合作者还有一些类似的研究，都发表在很好的经济学期刊上。比如有一篇文章讲PM2.5越高，Pear Packers的效率越低。这篇文章的主要贡献在于工人的工作环境主要在室内，即使有建筑保护，PM2.5也能进来影响工人的生差率，而之前人们通常认知空气污染只会影响户外人群。还有一篇文章发现AQI越高，携程客服的效率越低，这篇文章主要的贡献在于之前的研究都是侧重于体力劳动者，而这篇文章的侧重点是劳力劳动者。

独特卖点，其实用一两句话就可以讲清楚。在之前文献基础上，找独特卖点。而不是找一个宏大问题但是只复制别人做过的工作。

文献非常熟悉。我们生产率的数据来源是中国工业企业数据库。这个数据算不上特别独特的数据，很多人都有。熟悉的人都知道这个数据库包含了中国规模以上及所有的国有企业，在我们的样本区间1998-2007有接近50万家企业。卖点就是在external validity上面，即外部有效性。之前我列到的文献都是用的一家企业或者一家工厂。好处当然是有非常详细的变量，但是缺点也很明显，因为我们不知道他们的estimate是不是对不同行业不同企业都有效。而环境规制政策导致的污染下降肯定不是只针对某一个行业或者某一家企业，所以我们在文章的第一段就讲到我们的主要贡献是提供了之前文献估计的外部有效性。

我们的文章投到了EJ之后，主编是Estelle Cantillon。她是做IO的，提了一个非常好的建议。之前的文献因为数据只是一家企业或者工厂，只能看局部均衡partial equilibrium，即只能看空气污染对生产率的影响。而我们的数据涵盖了制造业很多部门很多家企业，那么能不能看看一般均衡generalequilibrium，即空气污染上升导致生差率下降，而生差率下降可能会导致空气污染上升，进而有影响生产率的变化。这样就是一个互相影响的动态模型。主编的话我们敢不听吗，所以做了大量的修改。从之前的局部均衡到现在的一般均衡分析， 工作量至少增加了一倍。但是文章的贡献也更加深入。

## 分析 

好题目慢工出细活。实证最重要的就是因果识别Identification，常用的方法无非DID, RD, IV等。

我们这篇文章主要有两个因果估计，一个是空气污染对生产率的影响，另一个是生产率对空气污染的影响。

这俩部分估计其实还好，因为文献里面已经有了现成的方法，所以我们在因果识别这块倒是没遇到非常多的挑战。

首先是空气污染对生产率的影响。空气污染显而易见是内生的，如果我们看空气污染跟生产率的相关性，会发现它们是正向相关的，因为很多生产率高的地方像经济发达地方通常污染越高。所以我们要给空气污染找一个工具变量。过去关于空气污染对经济活动影响的文章非常多，所以有不少可供选择的工具变量，比如逆温、风向、一些政策冲击像美国的清洁空气法案等。我之前有很多工作用了逆温做空气污染的变量，主要是数据易得，操作起来也比较简单。

然后是生产率对空气污染的影响。这方面我们用了贸易文献中常见的中国加入WTO加上沿海省份vs内陆省份的DID setting，用其作为生产率的IV。

我们在分析中遇到的最大难点是如何建立一般均衡模型，因为没有文献可以参考。没有很好的切入点。我因为休息不好一直喜欢在睡觉前想论文。有一天晚上突然想到可以借鉴Nordhaus的DICE模型。DICE模型主要是针对二氧化碳，而且有大气模型，我们不需要这么复杂，因为空气污染不像CO2一样有一个在大气中累积的过程。有了参考之后建模就顺利很多。

当然在分析中还遇到了很多细节问题，但我个人感觉这些都不是很大的挑战，顶多多看看文献教科书还是能解决的。

我的一个经验是在分析中要把自己带入到审稿人的角色，看看每一步是不是能说服审稿人，而且很多细节很多稳健性检验要非常注意。我们自己做审稿人看别人文章的时候也是很容易看出文章的工作量的。

## 写作

写作也是一个非常重要的环节，尤其是Introduction部分。

这部分写得好不好，跟选题有很大的关系。如果对文章的贡献非常清楚明了，其实也还是挺好写的。

第一段通常是引入题目，说明研究问题的重要性。

我一般推荐直接引入文献，不推荐写一些空话。比如我们文章第一段刚开始就简单的引用了过去的文献，说明他们的贡献和局限，这样才能引入我们的贡献。当然我们第一段也可以开始写空气污染的严重性之类的，但我感觉这样的内容没有什么意义，因为审稿人都是这个领域的专家，都知道治理空气污染的重要性。我一般作为审稿人看到这样的文字基本上就跳过了。

第二段开始写自己做了什么，为什么可以解决之前的问题。如果能有 This paper is the first study on …就很好了。如果审稿人看完前两段还不知道这篇文章要干什么贡献在哪里文章基本上就没戏了。

接下来就没有什么固定的格式，基本上写写数据来源，识别策略，主要发现，主要机制之类的。

很多人包括我自己在接下来会把自己的贡献再讲一遍，因为一篇文章的贡献通常不是一点。

有时候会说This paper contributes to several strands of literature，里面会跟第二段有一些重复，我觉得没关系。

除了主要贡献外也可以讲讲其它贡献，比如我们文章第一条贡献是讲external validity，第二条是讲general equilibrium，第三条讲了我们的一些一致性分析的结果，因为之前文献做高技能行业相对较少。最后我们还讲了中国setting的重要性。这里有一点，千万不要说这个题目美国做过了，但是中国还没有做过所以我们要写这篇文章。这可不是贡献，因为只是一个Application，没有原创性。可以讲讲中国setting有什么比较有意思的地方，或者中国作为发展中国家institution跟美国有什么不一样的地方等等。

总之写作是对文献理解、文字掌握、政策解读等。

四、投稿

多投会议，去不同地方讲。尤其是底下的听众有可能是审稿人的。多搜集意见，多改，一定要文章非常非常完善了之后才投，而不是随便写写就去投，这样一个会影响个人reputation，另一个能投的期刊其实非常少，浪费一个就少一个。

大家应该对经济学的期刊排名有一个大致的了解。经济学期刊很少看影响因子，也很少看是不是SSCI，基本上公认的期刊就那么几十本。最牛的是top 5，即American Economic Review, Econometrica, Journal of Political Economy, The Quarterly Journal of Economics,and Review of Economic Studies。接下来是一些general interest期刊，比如AEJ系列，EJ, JEEA, REStat等，还有field journal，像JOLE, JPubE, JDE, JIE, JME, JOE, JET  > JEEM,JHE, JUE算成A-。 

现在很多经济学杂志的desk rejection rate都在50-70%，所以能送审就打败了一半以上的文章。审稿报告总体上还是挺积极的，里面提到的一些问题都能改，但是主编热情不大，最终还是拒绝了。我之前也跟一些主编聊过，现在通常的审稿报告都是2-3份。如果都是正面的，那基本上主编都会给RR。但是大部分的时候都是一正一负，或者两正一负，这种情况下主编的意见就会起到决定性的作用。收到审稿意见之后虽然文章被拒但是如果审稿报告里面有合理的意见还是要尽量的修改。我们又做了一些修改之后投到了EJ。EJ系统里面可以选择Editor，这个挺重要的，大家可以仔细看看主编的研究领域，尽量找领域接近主编。

回应主编跟审稿人意见几个原则。一个是态度要友好，除非审稿人发了非常严重的错误，不要跟审稿人辩论，让做什么就做什么，并且要很感激的表达出他们的意见对文章进一步提高的重要性。另一个就是能改的要尽量改，实在改不了了就只能解释为什么做不了，但是态度还是要端正。最后一个就是主编的意见是最重要的。有些主编会在decision letter里面写的非常清楚，像我们这篇文章的主编就按照重要性列个六个意见，非常清楚明了。
