---
title: "Writing05-Trilogy of High-Quality Economic Paper Writing"
description: |
  学术性的写作
author:
  - name: Yang YAO
    url: 
date: last-modified
categories:
  - 英语
  - 写作
  - "2023"
image: ""

---
我自己做研究十几年时间，也有一些心得，所以今天就跟大家分享一下这些经验和心得。我今天的讲座主要有两部分，我要讲的第一部分是论文发表的三部曲：选题、技巧和写作。

一个好的选题是一篇论文成功的一半，但不是每一个好的选题都能做成。技巧就是我们所受过的训练，我这里会讲一下自己的心得。最后一点是写作。经济学从本质上来讲还没有完全摆脱文学的性质，所以写好一篇文章还是很重要的，我们还没有达到像物理学和化学那样写一个实验报告然后就可以发出去。以前我不知道，后来跟一个研究化学的聊了一次，谈到他们在 Science 和Nature 上面发表文章，编辑部觉得你的结果基本上可以了就给你发了，根本不管你写的如何。我们经济学还没有达到这一步。同时他也告诉我说，Science 和 Nature上每年要发表上千篇文章，在这上千篇文章中可能只有百分之一是有用的，其他文章很快就会被人忘记。我们经济学写一篇文章要比他写一篇实验报告费事很多，所以也不容易被人忘记，这也是一个好事情。讲完这些之后，我会举三个例子，都是我自己的研究，并不是我的研究有多好，只不过是我知道我是怎么走过来的，这是很重要的，因为有时候你看别人的文章但并不知道他是怎么写出来的，所以我可以谈一些我自己的感受。一篇是关于中性政府的文章，发表在《经济研究》上；第二篇是关于政府基础设施投资与居民消费，这篇文章我们刚完成，会在一本英文刊物上发表；最后一篇是市场化与党的精英化，这篇文章我们还在写，在此我只是给大家提一下。

第一部分：论文发表三部曲

1.选题——好的选题是论文成功的一半

首先说选题，我们做经济学研究，题目非常多，那么什么样的选题算是一个好的选题呢？我觉得在中国做经济学研究，还是应该以问题为导向。当然有些人会说我的志向就是要拿诺贝尔奖，我就要做纯理论的问题，但我感觉中国人做这种纯理论的问题没有比较优势。

没有比较优势怎么说呢？林老师喜欢说一个例子，经济学的重镇以前是在英国，后来随着美国经济的崛起，经济学也就转移到美国，但是这个过程是非常漫长的。我们知道，美国在 GDP总量上超过英国是在 1896 年，在人均 GDP 上超过英国是在 1914 年。那么经济学的重镇是什么时候转移到美国的呢？我们一般说是 1947 年萨缪尔森发表《经济分析基础》那本书之后。从美国人均 GDP 超过英国，都经过了三十多年。我们比较乐观的估计，十年之后中国的 GDP 总量超过美国，那就是 1896 年到 1947 年，大概也要五十年的时间。你要看经济学重镇的转移啊，要从 2020 年开始，我们再等 50 年，大概经济学的重镇能转移到中国来。这是一个判断，中国要成为经济学的重镇，从现在算起还要等很长很长的时间。第二你要知道美国大学里面的经济系，是一个很强势的学科。他有多少的人天天没事干，天天就研究这东西。李稻葵老师老喜欢说，美国为什么把经济学搞得这么复杂，本来经济学是没有这么难的，就是因为收入很高啊！劳动力市场上工资高了，就要提高门槛，怎么提高门槛呢？就是要搞你的智力测试，对你的智力要求越来越高。所以在美国搞经济学研究的一帮人智力很高，都极端聪明，像克鲁格曼这种人，极端聪明、极端自负。他天天没事干，不像我们，国内事情特别多。他天天坐在办公室，没事干，天天在琢磨一些经济学的问题。还有很多博士生，也在干这个事情。你想去竞争过他们，要在纯理论上有所突破，我估计是很难的。这不是说我们不行，事实就是这样的。人家环境比我们好，花的时间比我们多，所以我们的比较优势还是在中国的实践，看能不能从中国的实践中提出一些问题，来好好的研究，一定是问题导向，这点我觉得特别特别重要。

我收到很多文章，看了他的前言和摘要，这篇文章大概就不会发表了。现在有了刊号之后，投稿数量大一些，我们每年大概会收到七八百篇文章。我们送审的就有三分之一，三分之二的文章，我们三个主编看看就给拒掉了。我们很多时候是在看摘要，这不是说我们不认真，因为你一看他的摘要，就发现里面什么也没说，所以只能给拒掉。送审的三分之一再拒绝一半。所以选题是非常重要的。你能不能在中国找到一个有意义的选题，别人研究过但你有好办法，或者别人根本没有研究过。在这一点上，作为中国的学者是有优势的。中国在过去三十年间发生了翻天覆地的变化，中国是世界上最大的发展中国家，中国现在是世界第二大经济体，有很多有意思的东西。中国法治不健全，很多东西都在变，不停的变。这实际上是一个大实验场，我们应该有很好的素材要去挖掘。我就发现，我们收到的一些文章，很多人喜欢探讨一些纯理论问题。比如我们老收到关于科斯定理的文章。我就想，科斯定理都被研究了几十年了，难道你还能发现新的东西？我觉得不太可能，所以这种文章，一看就给拒绝掉了。你能不能说中国现实中有一个事情，你能拿科斯定理或者科斯定理的延伸去解释。所以还是问题导向，这也是最有可能发现新的问题的地方。

什么是好的选题？

什么样的选题是好的选题呢？第一是要有新的理论构想，我刚才说了你要去做纯理论的东西不是很容易，还是要问题导向。你一定是在现实中发现了一个什么东西，但现有的理论解释不了，你才去发展一个新的理论。我不知道在座的有没有博士生，大家看起来都很年轻啊，我拿到文章最忌讳看到什么样的文章呢？一个已有的理论模型，他把人家的假设改一改，推导的非常复杂，最后推导出的是一个非常 trivial 的东西。你改已有模型的假设，往往你会改错的。这一次我们碰到一篇文章，说克鲁格曼的中心外围模型（Core and Periphery Theory）的理论错了，说克鲁格曼的文章中存在重大的错误，他指出来两点，我们差点接收了。还好我看过那个模型，很明显是他自己搞错了，他对那个问题并没有那么熟悉。你仔细想，克鲁格曼的那是得诺贝尔奖的文章啊，他要是有那么大的错误，还能得诺贝尔奖吗。不要高估自己的智力，克鲁格曼是绝顶聪明的人。

不要老去拿别人的模型，改一改假设看能否推出新的东西，千万别这么做。你要是写过理论模型就知道，一个理论模型都是磨了又磨，磨了又磨。为了得出他需要的结论，假设已经简单的不能再简单了。然后你去改他的假设，完全就是两码事，不可能做到。我以我们还是要从现实中发现有意义的题目，而不是纯粹的去改人家的理论模型。你比如说中国经济为什么成功，这个问题当然很大，不管你是做哪一个领域，你在你那个领域里头都可以问这个问题。在我这个领域，我如何解释中国经济的成功，现存的解释有什么不足。比如说，我们通常认为腐败不利于经济增长，而且有很多很多的理论和经验研究都证明腐败不利于经济增长。我们知道中国腐败很厉害，透明国际（Transparency International)给中国打分，廉洁指数（CPI）中国都是最低的百分之三十，但是为什么中国的腐败至少没有阻碍中国的经济增长？如果你是研究制度经济学和新政治经济学的，这个问题是不是可以挖掘下去，我觉得这里面有很多可以做的。为什么在中国腐败没有成为阻碍经济增长的因素，是不是能挖掘一下？

第二个选题就是解释一个谜或者意外。谜就是逻辑上无法找到答案的现象，你比如李约瑟之谜。大家知道李约瑟在写《中国古代技术史》这套书的时候，他提出来一个问题，中国古代技术水平到了如此之高的地步，但为何近代的工业革命没有发生在中国，似乎在逻辑上没有办法解释，当然就这个问题有很多的研究。

另外一个例子是，中国具有巨大的外汇储备，但我们为什么还要外国直接投资呢？我们实际上还在出口资本，那为什么还要外国资本投呢？这都显然是出现了一个问题。再往回看一步，中国的投资回报率实际上是非常高的，如果你能找到项目去投资，回报率可能都是 10%以上。如果是这样的话，为什么我们会有经常项目盈余呢？为什么这些钱没有投在中国而是要变为外汇储备给别人用呢？投到美国我们的回报率是多少？每年是 2%。你到中国的民间信贷市场上去，现在年利率都是 20%以上。这显然是某个地方出问题了。我们现在老说中国经济失衡，那我们能不能深入的问一些这样的问题，找到一些这样的谜，然后来给这些谜一个解释。其实中国这样的谜很多。再比如中国的法治环境非常糟糕，法院判决了也不执行，那为什么还要签合同？我到企业去调研，发现他们基本都要签合同。而且法治环境那么差，但是经济表现并不那么差，这里面到底是什么在起作用。

再一个就是意外，你发现了和现有理论预测相左的经验事实。理论上说随着价格上升需求会减少，但你发现价格上升需求上升的事实，这是经济学上一个经典的理论，你是不是有不同的解释。总体上来说，文章要想发表，一定是你可能构建了一套理论对现有的东西进行解释，也有可能是你发现一个谜或者一个意外，这样你的问题才能抓住审稿人的眼神。这样你的文章就成功了一半，因为你发现了一个很好的问题，然后你又给出了一个解释。科斯研究所（The Ronald Coase Institute），其实就是一个很小的研究所，有几个人在做，领头的叫利·班南（Lee Benham），他办学习班给年轻人的要求就是，第一要有一个 big“wo”，“wo”就是“喔，我没想到”，也就是一个惊喜；你又能给出来一个看起来合理的解释，我是说看似合理的解释，别人看了说“哦，啊哈”，这就是能把别人的眼神给抓住。

第三个方面，应用现有的理论来解释现象，你比如说检验现有的理论。有很多理论，前人没有检验过。然后你有新的数据，新的计量方法。比方说最近在国际经济学界比较热的是做 Emprical IO,以前做产业组织基本上都是理论模型，但现在来说理论模型做的差不多了，大家都开始做检验。用数据去检验，这个是现在很热的东西。新的数据也很重要，我们这里收到的很多文章，如果他真的是用微观数据做的，被拒绝的概率是极低的。一篇用微观数据做的文章，在我们那个杂志，特别是经过我的手的，大概就有 60-70%的成功概率。中国现在的微观数据极少，现在通常我们做微观研究可用的数据就 2 个，中国居民家庭收入调查（CHIPs）和美国北卡大学中国研究中心主持的中国健康和营养调查（CHNS）。其他的数据都没有公开，统计局和农业部的数据，都需要花钱买，并且都很贵。

我在这里做一下广告，我们北大有两个数据，一个是赵耀辉老师领导做的CHARLS，主要做退休和健康的数据，现在已经做了两轮，一个是甘肃的，一个是浙江的，这个数据在CCER 的网站上就可以查到的并且免费下载，大家可以去用。在网上就可以免费下载到，这个数据对我们做应用微观研究的学者是有很大帮助的。另外一个是中国家庭动态调查（CFPS），由于数据库是北大出钱做的，所以北大先用，然后再对外公布。如果你有北大的朋友，你们可以合作。我想这两个数据，过几年以后就会成为金矿。我现在看到的就是，CHIPs 和 CHNS 已经被大家用烂了。无数的微观文章，都是用这两个数据。还有一个就是新的计量方法，如果你做这个也是一个很大的贡献。对我们来说做出新的方法论不太容易，但最简单的内生性问题，你如何来解决，这是可以做的。

再下面一类就是应用微观计量学，用微观经济学理论解释现象，并用数据做出证明。这个往往需要你写一个小的理论模型，因为你是应用微观经济学的理论解释现象。一个简单的例子，农村新型合作医疗是否降低农村信教的概率，我们知道人们信教其实是为了减少不确定性，信教最关键的不确定性就是死后你不知道你在哪里。其实宗教就是利用未来这种未知性，所以所有的宗教都是关于来生的。我们知道最近这些年中国农村信教的人越来越多，那到底是什么原因导致的呢？一个可能的原因是不确定性太大了，所以人们要信教。这篇文章是中国人民大学的郑风田老师做的。其实他们用的数据不是特别好，是河南省开封地区的一个局部数据，但我看到这篇文章的时候，我眼前一亮。这是个很好的也是非常显著的问题，特别是这种外来的宗教，基督教、天主教在中国农村扩散的非常非常快，这对中国农村是有影响的，他又和新型农村合作医疗结合，新农合是不是可以降低信教的可能性。这个问题非常好，其实因为数据的原因做的并不是非常好，只有几百个农户的数据，但我还是愿意给他发，我觉得他提了一个非常显著的问题；当然他没有写一个模型，其实这种情况下最好简单的写一个模型，还可以有一些简单的预测，这样会更可信一些。

不好的选题

第一个是我刚才说过的改别人模型的假设，这种情况一定要杜绝。我拿到这种文章就觉得纯粹是在浪费时间和精力，因为解这样的模型通常很累，而且最后发现错了。

第二种是生搬硬套别人的理论模型，没有把经验事实给搞清楚。先把你要讨论的事实给搞清楚，然后用已有的理论去解释你的问题和事实。关于中国过去土地制度的变化，从秦始皇到现在的土地制度，我们经常收到讨论这类问题的文章，往往是生搬硬套科斯的产权理论等。做这样的文章，你不去不扎扎实实阅读一些历史书籍，不去看一些数据，而是生套别人的理论，可以说是毫无意义。所谓研究，就必须要做出自己的东西。格雷夫在研究马格里布犹太商人的合同执行问题时，他挖掘很多中世纪的合同去研究，真正的做了一些历史研究，而不是生搬硬套现有的理论。

第三个是关于稻草理论，为什么叫稻草理论呢？二十世纪初对欧洲的知名知识分子做了一项调查，在过去一千年，人类什么样的发明对人类的进步起了关键性的作用，有一个人给出的答案是稻草，为什么是稻草呢？他说如果没有稻草，你就养不了马，养不了马就没有办法去打仗，于是欧洲的文明就拓展不开来。所以没有稻草就没有今天的欧洲，所以稻草是最重要的发明。你说他有没有道理呢？道理是有一点，但是被无限放大了。这样的理论就可以说是稻草理论，其实并没有那么显著但是被夸大了。

还有一个常见的问题就是研究决定因素，我最怕看到这类文章。花了好大的劲，最后做了一篇例如工资是由什么决定的。这种文章最好别做，你在回归方程里放十个变量，我可以说你的变量不够，你应该放二十个，那二十个可能还不够，你得放上一百个变量。这个都是由很多的因素决定一个，你能把所有的因素都能穷尽吗？有些人说我做了一个实验，刚开始时二十个，后来发现有些因素不显著，我把它给去掉了。然后重新放，发现又有一些不显著，又给去掉了，最后这些因素是最显著的，所以我留下来了。这不是做研究的方法，我们一定是研究一个机制，控制其他变量把一个机制说清楚就可以了，比如你可以问工会对工资有没有影响，你只要把这个因素搞清楚就可以了，而不是说非要去研究工资有哪些因素决定。这样的问题不是一个好问题，不容易在好的期刊上发表。

2. 论文写作技巧

现在我想讲一下论文写作技巧方面的问题，我想从两方面来谈这个问题，一个是理论研究，一个是经验研究。如何做理论呢？有很多人说我做理论啊，就是写出一个模型来，模型推导出什么结果就是什么结果，这种情况是没有把经济学给搞懂。做经济学的文章，你一定要有一个符合直觉的故事，先把你的故事用自然语言表述出来，如果你的故事没有办法用自然语言表述出来，那你肯定是什么地方出现问题了。首先用自然语言把这个故事讲出来，一定是你已经知道你要的结论，然后去编一个故事，不是你写一堆假设，然后推导出一个模型来，推导出什么结论我就接受什么结论，这是完全错误的。哪怕是数学家也不是怎么做的。

你试想阿罗当年在写阿罗不可能定理的时候，他难道事先没有把这个结论想好吗？难道是从他的四个假设出发最后推导出他的不可能结论的吗？肯定不是这样的，他肯定是有个直觉告诉他这是不可能的，然后再回过头来，找最小的假设的集合。结果发现，必须有这四个假设，才能推出所需要的结论。其实其中有些假设基本上很难符合事实，你比如其中有一个两两不相关原则。我刚到美国的时候，美国总统大选有三个候选人，老布什、克林顿和罗斯·佩罗（Ross Perot）。根据两两不相关原则，意味着老布什和克林顿两个人的排序不受老布什与佩罗排序的影响，也不受克林顿和佩罗的影响，这在现实中是不对的，但是他必须要这个假设才能得到他的结论。他是倒过来想的，其实数学家也是这样想问题的，你比如说数学里有很多猜想，比如哥德巴赫猜想，是先有这样的猜想然后才证明出来的。

我以前也不知道，我跟我的第一个导师做研究，写理论模型老写不出来。后来我碰到一个学数学的同学，我就问他我想得出一个结论，怎么能得出来？这位学数学的同学一句话，使我茅塞顿开，他说在数学上想要什么样的结论都能得到，看你的假设是什么。数学上有一大堆数学的公理，你不能超出这些数学的公理的假设。经济学稍好一点儿，经济现象太复杂了，你可以做一些假设。但是你一定是先有结论，后写模型，把这个故事讲圆了，而且这个故事要讲的精巧一点。然后你要找到适当的经济学模型，用严谨的数学语言把故事用表达出来。

这里有两个关键词，第一个是用适当的经济学模型。最好使用现有的经济学模型，就能把它给讲出来，模型又比较精巧，然后你还能用数学语言讲出来。什么叫恰当的经济学模型呢？如果你是做制度经济学或者新政治经济学研究的，那应该知道最近几年一个火的不得了的人，他叫达龙·阿西莫格鲁（Daron Acemgolu），他几乎所有的文章都很精巧，他有一篇文章“Why Did the West Extend the Franchise?”，就是说西方民主化过程是怎么走过来的，西方的民主化过程并不是短期内完成的，英国大概花了 220 年的时间，一直到 1928 年妇女才拥有跟男人同等的选举权4。他讲了一个什么故事呢？他就讲穷人跟富人之间的斗争，穷人斗的厉害，要自己的利益，富人就放一点。我们完全可以用马克思的阶级斗争来解释，但是你要用马克思的阶级斗争来解释，别人就不认，至少从现代经济学的眼光来看，这不是一个理论或者是不能接受的理论。所以他编了一个故事，他编的是一个 Commitment（承诺)的故事，当穷人向富人要福利的时候，富人说我给你，但是决定权还在我这里。但是穷人一想，你答应给我，到头来你又不给我，怎么办啊？这里面其实是一个承诺问题，怎么实现这个承诺呢？富人说干脆让你们穷人决定，这不就是民主吗。你自己决定该怎么干就怎么干，我不管了。这个故事就是一个经济学的模型，这也是 Edward Prescott 得诺贝尔奖的模型。但我觉得根本没有必要这个模型，马克思的阶级斗争理论完全可以解释，而且可能解释的更充分。但是你最好写一个经济学的模型，讲一个经济学的故事，别人可能更容易相信。

那好，大家会问这样一个问题，你既然可以用自然语言表述出来了，那为何还要用数学模型来表达呢？我觉得唯一的原因是自然语言有漏洞，自然语言没办法表达清楚，特别是汉语。比如我坐在这里讲，语法上错误连篇，汉语就决定了你可以不讲很严谨的语法，但英语你要是不讲语法别人就听不明白。英语比汉语更严谨一些，但是我觉得汉语写诗要比英语好的多。据说法语更加严谨，但是再严谨的自然语言它都存在漏洞。你有时候听一个人用自然语言讲得天花乱坠，但是要真写到模型上来，可能写不出来，会有很多的磕磕绊绊。举一个最简单的例子，我刚说了中国资本回报率很高，但是我们又输出资本，你怎么去解释这个问题呢？你用自然语言可以说出来一个比较简单的故事，你可以给出一个解释。我们有些企业从银行贷不到款，有些企业从银行贷到很多款，所以这里头总是有企业得不到贷款，所以一些贷款就会流到其他地方去。这样听起来似乎是有道理的，但是你要写一个模型你试试，它不是那么容易的。这样的模型，你通常要用到 ORG 模型（Organization Generation），而且你一定要加入银行它有一些问题，你必须用经济学理论模型思考的时候，你才能发现一些你想不到的东西，这是非常重要的。

经济学模型的作用，一是检验理论的逻辑，再者是发现新的东西。但是不是模型就一定是真理呢？特别是做应用型研究的时候，不要把模型当做真理，它只不过是跟一种自然语言替代的描述方式。我老跟学生说，数学就是另外一种语言。数学家可以很简单的用英语、法语，他写的这些数学论文，大家都能看懂，不需要多少文字。所以数学它是一套严谨的语言。这里说到经济学，我个人感觉，还是解释为主，而不是去做预测，我们只不过是讲一个故事，就像历史学家也在讲很多故事，经济学家用数据和模型来讲这个故事，都是描述历史。我们描述短期的历史，历史学家描述长期的历史。怎么知道一个理论模型是好是坏呢？首先要看这个假设是不是合理。我刚才说了经济学家可以卖一点狗皮膏药做出一些假设，但是你的假设如果太生硬，特别是理论文章，马上就会被砍掉。我老说，这是短路了。你做了一个假设，然后做了一大堆复杂的推导，结果发现只是这个假设在起作用，当然这种模型肯定是不行的。

第二个要看你的模型应用是否得当，就是你是否用了正确的经济学模型，逻辑是否清晰。有些模型写的很复杂，估计自己都没整明白，一定要写的清晰，要有血有肉。模型是否精巧，你不能写的像大白话，你比如我之前说的，阿西莫格鲁加入 Commetment，显得更精巧一点。结论是否符合直觉，如果结论不符合直觉你的模型显然是有问题。你做出来结果发现跟我们的直觉的不一样，要不就是你的假设错了，要不就是你的逻辑有问题。是否能从现实中得到一般化的结论，这也是检验理论的一个重要标志。最后一个标准时结论是否经得起数据的检验，当然这个要求有点高，其实很多经济学模型就是表达一个 idea，不一定非得要用数据来检验，而且往往是这套数据检验不成立，我用另外一套数据。数据很多，世界是多样化的。

经验研究

经验研究，好的数据是第一要务，我刚才说的这几个数据库都是公开的数据。省级的数据，现在基本上都被大家用烂了，除非你有好的 idea，我建议大家少用省级数据。花一点时间收集县的数据、城市的数据，这些其实是可以收集到的。我知道有一个人在北京图书馆呆了一个夏天，把县的数据全部给整出来了。我现在有一个博士生，他现在在收集城市的数据，他要研究官员的升迁问题。收集这些官员的来龙去脉，天天在网上查资料，做研究一定是要自己花点功夫和时间，做出一些出人意料的东西。像我这个学生，他有了这么多城市、这么多官员的升迁的数据以后，我估计吃十年是没有问题的。

经验研究也要讲一个故事。有人说我拿数据扔到模型里头，我一回归出来什么结果就是什么结果，这就是垃圾进垃圾出啊。一定要有故事，最好要有理论模型。当然理论模型不是说你要构建一个理论，而是说提出一个分析框架，哪些变量是解释变量，哪些变量应该作为控制变量，没有理论模型，这些东西你还真整不清楚。写完理论模型你的思路会整一遍，你才知道放什么变量。

另外，要从多个方面验证自己的结论。好多人做经验研究，两个回归就结束了，然后就是结论。我们检验理论预测，我们往往是检验一个理论预测，但是数据支持理论不一定就说理论是对的。因为你无法排除，其他理论也能得到你观察到的数据，就所谓的 AlternativeExplanation（非唯一解）。所以你要不停的问自己，是不是存在其他理论解释你的经验发现。你就是想象有一个审稿人，他在挑你的错误。现在国内好一些的杂志都在推行审稿人制度，我通常也要给一些杂志写审稿报告，拿到文章第一直觉就是把这这篇文章给杀掉，杀掉以后后面就很省事了。

《经济研究》每年的投稿量要上万，他一年能发表几篇文章啊，他不砍掉你才怪呢。所以要想发表一定是一个非常好的问题，方法经得起推敲。你可能还要检测一下反面的结论，我们的理论模型往往是一个正面的结论，是不是还会有一个方面的结论呢？我们做过一个这样的例子，村庄选举增加村干部为村庄办事的积极性，这是正面的结论，但是他没法解决小孩上中学的问题，那你有数据说明村干部确实为村民多修了桥，多增加了灌溉设施，但是按理说他不应该对小孩上中学有影响，所以你是不是应该再做一个回归，看是否对孩子上中学有帮助，如果没有帮助最好了，如果有帮助，那估计是存在问题的。因为他本来不应该有帮助，但是你做出来的结果是有帮助的，这种情况有可能是你的数据出了问题。

做经验研究，一定要注意内生性问题。现在要求也越来越高，国内也是这样，如果你不能解决内生性问题，你要在好的杂志上发表是很困难的。一个是伪相关，两个变量之间完全来自于偶然因素表现出相关关系，一个经典的例子就是街上流行红裙子股票就涨，这两个毫无关系的。时间趋势，有的完全是时间趋势，特别是你做省级的数据，最好控制时间趋势，不光控制所谓的年度哑变量，你应该控制各个省的自己的一个时间趋势，省的哑变量乘上时间，这样就可以控制时间，我这里说的时间是日历时间。还有遗漏变量的问题，遗漏变量就是有些变量没有控制，最简单的情况就是你在不控制收入的情况下，需求可能是价格的增函数。控制了收入以后你会发现需求是价格的减函数。

一个朋友说到他的一项研究。他这个问题其实还不是遗漏变量的问题，其实是反向因果关系的问题，他说农户之间土地租赁合同时间越长的话，租户对土地的投资就越多，从理论上来说一点问题都没有，产权的稳定性对投资的影响，产权越稳定，当事人越愿意对土地进行投资。但是你如果用数据检验，就会出问题，你比如说我是一个租户，我为什么要麻烦的签一个长期的合同呢？有可能是因为我就是想在土地上进行长期投资，所以才找来一个土地所有者说我们来签订一个长期合同来保证我的权益，我恨不得签十年。这样的话你如果拿一个长期的合同作为一个投资的解释变量就错了，实际上是因为我想要长期投资，所以我才签了一份长期合同，这就是一个反向因果关系。所以我们做经验研究的时候，要把这些问题给想透。

总之，做经验研究的时候，永远记着有一个审稿人坐在你对面，问各种各样的问题，然后你应该想方设法的用你的计量结果来回答他，就是审稿人可能这样问，我有没有一个办法可以解决他这个问题。你不要做一个鸵鸟，认为细小的地方审稿人看不出来，这样你就错了，审稿人就是看这些具体的，如果他是一个有经验的研究者，他就看你有可能忽略掉的问题，然后他就把你枪毙掉。

3.优秀论文的写作

最后我讲一下写作。我刚回国的时候，林老师跟我说他 1987 年回国的时候，那时候没人跟他讨论，写国际期刊上发表的文章闻所未闻。所以他找一篇范文，按照八股文，依葫芦画瓢。这个也很重要，这里头确实是有些八股在里头。

有几个关键是要说清楚的，第一个是要说清楚文章在文献中的定位，开篇就要说。我刚才说的利·班南（Lee Benham），他要求年轻人说，你的摘要头二十个字念出来。英文单词头二十个可以说不少东西，如果你头二十个字说完了，别人还不知道你的文章要说什么，那你就是失败了。所以写摘要，一定要开门见山，把你想要写的写清楚，不要啰嗦。前言很重要，Referee（审稿人)一般都先看文章前言，然后看结论,如果他觉得你这个没意思，就给你砍掉了。所以一定要在前言里面写清楚，文章在文献中的定位是什么，你的贡献在哪里。

第二个要在前言里面把自己的故事说清楚，往往很多人都不写，遇到不耐烦的 Referee（审稿人)他就给你砍掉了。一定要记得在前言里面把你的故事讲一遍，如果你是做计量研究，把你的方法大体上主要的说一遍，把结论说一遍，有些人会说这样就会重复了，重复了不重要。不要躲避，要直面自己假设和数据局限，承认它们但认真的为自己辩护，没有一个数据是干净的，你也不要以为说审稿人期待你有很干净的数据。另外一个就是要在前言里面说清楚你用的什么数据，我们有些人写文章连数据来源都不说，这种文章肯定被枪毙。如果你不注明数据是哪里来的，怎么证明你的数据的可靠性呢？前言里面就要说，不要等到后面再说。要意识到自己的局限性并认真为自己辩护。条理要清晰，不要只写给自己看。特别是理论文章，你一有跳跃别人就看不明白，哪怕你以后要删除，你第一稿也需要一步一步来，你是写给读者看的，你要想象那个读者他可能不懂你的东西。如果你的很高深的东西，能写给不是你这个领域的人都能看懂，那你就了不起了。这是大师级的啊，实施起来当然是很难的。所以要时刻想象你是在写给读者看的，不是写给自己的看的。

最后一个是要尊重规范，文字要符合语法，这个是最基本的要求，但是我们很多人达不到。中文又很容易写的乱七八糟，中文的语法本身就是很松散的，有时候句子写的无穷长，读完之后你都不知道他在说什么。书写要精炼，要短句子。所以我跟我的博士生要求他们用英文写作，我是觉得如果你的英文写作上去了，你的中文就上去了。我们写不了复杂的英文，老美他写了复杂的英文他自己都看不懂。所以张炳森说他跟老外合作，老外说自己写了自己都看不懂就让他写。要学会用精炼的语言表达一个复杂的意思，这个其实也不容易。千万不要有打字错误，有很多人，写完之后看都不看就发出去了，摘要有错别字，这篇文章就被砍掉了。我写文章，写到最后至少要通读两遍。现在都电脑打字，打过去错字连篇的，所以这个还是重要的。引用也一样，出现在文章中的文献一定要在参考文献中出现，反之亦然，这个也要多次检查。

引用和参考文献的体例要符合刊物的要求。我编辑这个刊物，最头疼的就是这些作者到最后都不给你弄好，这是个态度问题，态度有可能决定你的成败。我看过 Referee 的 Report，很多人都说这篇文章写的不规范，因为引用的文章在参考文献中看不到，这就是一个污点，可能就是枪毙你文章的一个重要依据。你连这个都做不到，怎么能相信你的结论呢。图表也是一样的，按照刊物的标准制作，不要用彩色，我们现在还没有办法印制彩色的图表。这样一点一滴的说起来似乎很累，但你要是一开始注意做完你就不会觉得累；反倒是写的时候乱七八糟，回过头来再改的时候，那才会觉得累。

第二部分，三个经济学研究的实例

举三个例子，第一个例子是我和贺大兴发表在《经济研究》上的一篇文章。我不会去讲这个模型，我会简单讲一下我们是怎么产生这个想法的。一个观察就是相对于其他国家，中国的经济增长非常成功，发生赶超的国家有一个特点就是社会非常平均，其实发生赶超的国家都分布在东亚，东亚社会都非常平均，经济层面上都搞过土改，在社会层面上都没有如种姓制度等这类社会禁忌，社会流动性很大；另外发生赶超的国家都有强有力的政府。这两点是我们观察到的。社会平等能否解释中国经济的成功，这并不是说就是唯一的解释，而是说我能不能从平等的角度给出一个解释。你要给出一个新的理论，你只要解释一点就行了。我们把前面的观察联系起来，就是说平等如何通过政府行为促进经济增长，平等是不是对政府的行为有所影响，政府的行为又会促进经济增长。一个不平等的社会它如何阻碍政府采取好的政策，在一个不平等的社会中存在强势的利益集团，它有能力推翻政府，所以政府就要对它很好，政府要跟它结盟，要给它很多的资源，这样就会发生资源的错配。你把资源给了一部分人，这部分人未必是生产力最高的人，最后你的经济没办法发展。反过来，在平等的社会中，没有哪个集团拥有独立的权利能够威胁到政府的统治，这样的社会中政府就更加容易将资源分配给那些生产力较高的人。这样对政府的好处就是它自己捞的也比较多，你可以想象政府是一个坐寇，他坐地收赃，把猎物喂的更肥大一些，这种情况下反倒更容易产生经济增长。

对文献的贡献就是，给出对中国经济增长从平等到经济增长的一个新的解释。在文献中，就与 Joan Esteban 和 DebrajRay 他们在AER 上发表的一篇文章，对民主政体的研究，民主政体影响政府主要是通过游说。他们的模型其实是一个信号博弈（Signaling Game），政府决定给哪些人资源，但是他们不知道哪个集团的生产力更高，这是一个私人信息，这些集团就会发送信号。谁更容易发送信号呢？往往是那些财力更雄厚的，因为他财大气粗，有财力去游说政府，政府就会把更多的资源给他们，这样就会发生资源的错配。我们等于是给出了一个非民主制度下的解释。另外一个方面，我们这篇文章在一定程度上解释了中国经济高速增长与高收入差距并存的问题。你把资源给了能力比较强的人，那么就可能产生收入的分化。我们的模型选择一个重复博弈（Repeated Game）和马尔科夫均衡（Markov Equilibrium）。发表之后我们现在还在改进，希望不用重复博弈，把经济增长给写进去。现在的模型没有经济增长，主要是一个横向的比较，如果把经济增长写进去，就要有资本的积累，一旦有资本的积累，写模型就比较困难。

第二篇文章是我和陈斌开写的一篇文章，陈斌开原来是林毅夫的博士，现在中央财经大学工作。我们提的问题是基础设施投资有利于经济增长，但是中国政府的基础设施投资有可能超过了社会最优需求，从而可能降低居民消费。我们想解释的是为什么中国有这么大的储蓄，为什么会有经常项目盈余，我们这篇文章就想看看政府起了多大的作用。

我们知道中国政府起的作用非常大，投资很多，对经济是不是扭曲作用，问题的提出是基于这样的背景。当然最简单的想法就是一个直接效应，政府收税，将税收用于投资，就会挤出居民消费，居民消费自然就会下降。我们想看到的是一个间接效应，政府的投资会不会有扭曲。第一，政府可以得到便宜的银行贷款，政府用大量土地获得大量便宜的贷款，由于资金比较便宜，有可能投资过度。第二，政府之间的竞争可能导致超额投资，政府为了吸引企业投资，将基础设施建设的非常好。比如天津的滨海新区，为了打造良好的投资环境，要建一座世界上一流的歌剧院，邀请的咨询团队都是美国纽约林肯中心的人。我估计这个项目一下子十几亿就下去了，那短期内能不能见效呢？我想大概短期内是不会见效的，滨海新区本来没人住，你还期望北京人开车去滨海新区看演出。这是一类典型的竞争导致的过度投资。政府投资往往对工业企业有补贴，因为他吸引的都是制造业。我们看一下政府之间竞争主要是在竞争制造业，为什么竞争制造业呢？制造业迁移起来较方便，你不竞争，他就跑到其他地方去了，另外制造业的市场大。它不像服务业，服务业只能服务一个地区，市场容量有限，制造业的产品可以卖到本地，可以卖到全国，甚至可以卖到全世界去。但是制造业的劳动回报率要低，它比服务业和农业的劳动回报都要低，资本利润就会上升，但是资本所有者的边际消费倾向低。这些原因都可能导致居民消费比例下降。这里给大家看一副图，我们可以看到政府的储蓄率要超过居民的储蓄率。居民的储蓄率 37.5%，最近这些年政府的储蓄率都超过45%，所以政府的投资非常大。

我们这里的数据，是用的省份的数据，但我们有一个新的角度来看这个问题。基本建设投资里头有三项，一类是道路之类的真正的 Infrastructural 投资，第二类是资本性投资，最后一类是其他的投资（包括水库等），这样看的话它的投资主要是第一项，所以我们大概把它看作基础设施投资。我们首先做了一个简化式的回归（Reduced-form estimation），什么是简化式的回归呢？简化式的就是把你的解释变量放在右手边，被解释变量放在左手边，直接做回归。被解释变量就是居民消费占省的 GDP 的比重，右手边放基础设施投资占省的政府支出的比例，还有一些控制变量。vi 是省的固定效应， vt 是时间固定效应。我们控制了什么呢？第一个是政府收入占 GDP 的比例，这就是第一个直接效应（挤出效应），我们还控制了人均 GDP 和它的平方来控制结构转型，然后控制国有企业的劳动力就业份额，还有控制了国际贸易，这些都是可能影响居民消费的变量。我们这里并没有把所有的变量都放进去，你可以说变量还不够的，但我们这里主要关注的是基础设施建设投资比例，我们这里只控制主要的变量，并不需要控制所有的变量。所以我说做经验研究，也是要讲一个故事，而不是说要找出影响居民消费的因素，这是毫无意义的。我们得出的结论是，如果基础设施建设投资占 GDP 的比重上升一个百分点，居民消费占 GDP 的比重会下降二点八个百分点，这是一个很大的效应。

我们还要想象别人会问什么问题，一个是主要的解释变量的内生性问题，那我们滞后一年、三年来看，发现结果还是非常显著。考虑到里面会有一些发现经济周期作用，所以我们用 5 年平均的办法来做，发现结果也是很显著。还有一个就是是不是省的时间趋势，所以我们又考虑了省的时间趋势，就我刚才说的用省的哑变量，既省的哑变量乘以日历时间，通过这个把时间趋势给去掉。然后我们又换了政府的支出（而不是收入）来做，也是很显著的。为什么要换呢？按理说，基础设施投资占政府支出的比例，应该控制政府的支出，但是从省的层面上，政府的支出可能跟当地经济发展没有多大关系，因为中央的补贴很多，所以后来我们主要用政府的收入，结果都很显著。反过来，如果我们的故事是对的，我们说政府的基础设施建设投资会超出社会最优水平，但是如果由私人来投资就不应该有影响。于是我们把私人投资占 GDP 的比重给放进去，发现没有影响。从反面我们也要证明自己的结论。我们这里的这些控制变量，还有一个作用就是控制省如果用私人来投资他的最优投资水平应该是多少。

我们为了解释内生性问题，又做了一个动态模型。用动态模型就是要把伪相关给去掉，在右手边加上了因变量的滞后一期，这里是用 GMM（Generalized Method of Moments）估计的结果。我们还做了消费的量，有人会说，既然基础设施建设投资有利于经济增长，那它可能会刺激居民的消费，所以我们就看了一下居民消费倾向是不是受基础设施投资比例的影响，估计的结果显示对人均消费几乎没有影响。我们又看了一下对全国的影响，把左手边的变量换成一个省的居民消费占全国 GDP 的比重，发现也是一个负的数据，所以它对全国也没有影响。

我们又做了结构式的回归，结构式的回归有两个故事，首先第二产业比例会上升，另外利润率会上升。先看第二产业的变化，所谓结构式的回归就是一步一步的来做。从最后一个方程看起，基础设施投资比例会影响到第二产业的比例，上面一个式子是说第二产业的比例会影响到劳动收入占比，第一个方程说劳动收入占比会影响到消费占比，实际上这是一个递归的方程。下面的资本回报也是一样的，基础设施投资影响企业利润率，企业利润率又影响劳动报酬比例，劳动报酬比例影响到居民消费比例。

我们先看一看 SUR Model（似无相关回归），然后又做了一个三阶段最小二乘回归（3SLS）。两个相对照，三阶段的更为有效，但结果是差不多的，资本回报也是一样的。这类文章，我想说的是做经验研究，一定要很仔细很小心。我们这篇文章还不是达到了最严格的标准，还是有内生性的问题。为什么我鼓励大家使用微观数据呢？微观数据内生性的问题就会小得多。省级的数据，所有的因素都是互相影响的，你想找一个干净的变量是很困难的。我们这里也没有试图去找所谓的干净变量，更没有找工具变量，因为找不到，你只能靠 argue，所以我还是鼓励大家多用微观数据做计量研究。

最后一个例子，我想讲的是市场化与党的精英化，这个问题其实是一个很重要的问题。我们观察到在过去三十年中国共产党的党员人数增长了一倍。在 1989 年，一位华人社会学家倪志伟（Victor Nee），在《美国社会学评论》上发表了一篇非常有影响的文章。他提出来，随着市场化的进展，共产党对老百姓的吸引力将会越来越小。所以他就预测，共产党在所有的转型国家，影响会越来越小，党员人数也会越来越少。但显然中国和越南，所发生的都不是这么回事，那是什么因素导致在过去三十年间，党员人数增长了一倍？

现有的解释分别从需求方和供给方分别来分析。需求方就是说入党有回报，党员的回报其实是非常高的，有很多人做过研究。清华大学的李宏彬用双胞胎来做，按理说双胞胎生下来能力都差不多，一个入党了，一个没有入党，最后发现入党的收入要高一些。其实这里还是有问题，我想问一下为什么一个入党了，另外一个不入党呢？之所以入党可能是因为他能力比较强。双胞胎的能力也可能不一样，在家里可能差不多，但是到了外面就不一样。另外在家里可能也不一样，晚生一分钟的那个孩子，就可能没有他哥哥能力强。所以基本还是没有解决“鸡生蛋、蛋生鸡”的问题。但是需求方面的研究，基本上还是可以肯定，入党是有回报的。供给方面的分析是说党加强了一些方面的门槛，比如党更加的倾向于精英化，我们看到的结果也是这样的，高校里面发展党员非常迅速，特别是 985 高校，想入党的基本都可以入党。

供给方面的分析认为党需要精英人才来管理社会，所以它越来越趋向于精英化。我们的工作就是想在一个统一的框架中讨论党在市场化进程中精英化的倾向。我们的故事是这样的：给定市场化程度，党会把更多的资源放在哪里呢？它会把更多的资源投放到高租金行业中，也就是这些带有垄断性质的行业，提高这些行业的党员回报。为什么它会这么做？因为在高租金行业中提高党员的回报相对容易一点，因为有更多的租金去挖掘，或者说高租金行业提高党员回报的成本更低。如果一个行业非常竞争，你要提高党员收入是非常难。随着市场化程度的加深，这个倾向会更加明显，因为你要吸引有能力的人入党，就更要在高租金行业中提高党员的回报。我们想用数据来证明我们的结论，胡赟之，是我的一个硕士生，他秋天要去芝加哥大学学习，他已经做了一些，我不准备去讲。我们现在有一个简单的理论模型，这个理论模型不是要给出一个解释，而是为我们的经验研究铺路。但实际中，我自己在写这个模型的时候也感觉到，之前可能有一些没有想清楚的东西。只有真正写理论模型的时候才知道，问题的关键在哪里。我非常简单的讲一下我们的模型。首先说一下我们的结论和猜想：第一，党的组织资源向高租金行业集中；第二，高租金行业的党员回报要高于低租金行业的党员回报，党员人数也高于低租金行业，市场化导致党的组织资源向高租金行业进一步集中。

在这个模型中，考虑个人的能力是一个[0，1]的连续分布，高租金行业 H，低租金行业 L，非党员的工资是 Aδ，A 就是教育回报，党员的回报是一个 CES 的生产函数，它有两个投入，一个是你自己能力δ，另外一个是党的组织资源的投入 S，i 表示高租金或者低租金行业。我做了一个假设就是 Ai，可以看做是高租金或者低租金行业的一个标志，AH>AL。入党对你的能力是有一些损失的，你要投入一些精力到党的事务里面，这个假设主要是为了后面的结论。纯粹从物质利益的角度考虑，一个人要入党肯定回报要高于不入党的回报，不然是没有动机去入党的。我们就可以得到一个δ，小于 δ*的人他就会选择入党，能力高的人他自己奋斗就可以了，不需要入党。但是是否决定入党，还取决于个人的意识形态，有些人他就不喜欢党的诉求。我们这里假设意识形态与个人的能力没有关系，所以实际入党人数和满足入党条件的人数成一个固定比例关系。党组织面临一个最大化党员的收入之和的问题，H 行业的党员收入加上 L 行业的党员收入，组织资源有一个约束条件，这样我们可以得到一阶条件，然后我们也看了它的二阶条件。从一阶条件很容易看出来，党在高租金行业投入的组织资源高于低租金行业投入的组织资源，相应的高租金行业的就业者更容易入党，直觉就是党在高租金行业的组织资源投入相对比较便宜。第二个命题就是第一个命题的简单外推，高租金行业比低租金行业的党员更加精英化，当更多的组织资源投入到高租金行业的时候，更多的高能力的人就会入党，它的精英化程度就会提高。第三个命题是高租金行业的党员回报高于低租金行业的党员回报。命题四就是个简单的推论，党员更倾向于到高租金行业中去。市场化导致个人能力回报增加，就是A 会增加，以此代表市场化。

市场化有两个效果，党对个人的吸引力就会下降，因为市场回报增加了；但是党的组织资源变得相对稀缺了，因为竞争对手更强大了，这种情况下强化了当向高租金行业组织资源投入的倾向，这就是命题五。我们的数据，一个是 CHIPs 的数据，它的 2002 年的数据有很详细的党员数据；另外一个数据来自于 CGSS(China general social survey)，这个数据中还问到了你有没有提出申请；我们也用到了一个党内的统计，内部资料统计了从 1921 年建党开始到 2000 年的党员统计。

第三部分，总结经济学理论的目标是解释世界，不是预测和改造世界，这一点上我们要抵制教育部的要求。教育部老喜欢让我们搞预测，给领导写报告，领导要是有一个批示，那就是非常重大的成果。经济学还是解释世界，我们其实没有预测能力，像经济危机那么大的事件，根本没有人预测到。如果我们的目标是解释世界，那么就应该有的放矢，坚持问题导向的研究。做经验研究要有理论贡献，不是说拿一堆数据做回归，一定要问我的文章对理论有什么贡献，有没有一个新的发现，描述完一遍世界，要给人一个惊喜。在方法论方面，要有联想，经济学研究还是个高门槛，为什么门槛高呢？建立起不同理论之间的联系是不容易的，要建立起理论跟经验观察之间的联系就更为困难了。你有一个很好的经验观察，你用什么理论来解释，这并不一定容易，很多人就是卡在这里过不了关。所以要建立各种理论，经验事实，以及经验与理论之间的联想，我想这是发现一些别人没发现的东西的一个关键性的地方。最后要坚持片面而深刻，拒绝广博而肤浅，我们一定要承认我们的片面。你只要说一个小故事，解释一个机制就可以了，不要想着把所有的因素都一下子做出来。

有一次一个学数学的转过来学经济学，他说你们这些经济学家做的都不叫经济学，做的都太简单。我要做的是写一个模型，把世界复制一遍。我说你肯定是没把经济学给搞懂，如果你一个理论模型可以把我们生活的这个世界描述一遍，那你那个世界就是机械的世界。经济学没办法把世界描述一遍，做不到这一点，即便是物理学也没办法把自然描述一遍。物理世界机械的东西毕竟更多一些，但是这个世界中的经济活动，它不是机械的，它是人组成的，我们经济学家的任务不是去复制这个世界，而是去解释这个世界。各种不同的解释连在一起，我们才能反映一个真实的世界，在才是我们的世界。